/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paper;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Dell
 */
public class addque extends javax.swing.JFrame {

    
    public addque() {
        initComponents();
        getContentPane().setBackground(Color.CYAN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        que = new javax.swing.JTextField();
        mark = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        subject = new javax.swing.JComboBox();
        own = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add.setText("Add Question");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        mark.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jLabel1.setText("Question:");

        jLabel2.setText("Marks:");

        jLabel3.setText("Subject:");

        subject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CS", "OOP", "DS", "CS2", "OOP2", "DS2", "CS3", "OOP3", "DS3" }));

        own.setText("Owner");
        own.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                        .addComponent(own)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(que)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(que, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(55, 55, 55)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(own, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    
        
        try{
        String url="jdbc:derby://localhost:1527/question paper";
        String username="qa";
        String password="qa";
        String subi=(String) subject.getSelectedItem();
         Connection con= DriverManager.getConnection(url,username,password);
        Statement stmt=con.createStatement();
        if(subi.equals("CS")){
        String Query="INSERT INTO EXAM(QUESTIONS,MARK)VALUES('"+que.getText()+"' , '"+mark.getSelectedItem()+"')";
       stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Question added in "+subi+" paper");
       que.setText(null);
       mark.setSelectedItem("1");
        }
         if(subi.equals("OOP")){
        String Query="INSERT INTO OOP(QUESTIONS,MARK)VALUES('"+que.getText()+"' , '"+mark.getSelectedItem()+"')";
       stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Question added in "+subi+" paper");
       que.setText(null);
       mark.setSelectedItem("1");
        }
          if(subi.equals("DS")){
        String Query="INSERT INTO DS(QUESTIONS,MARK)VALUES('"+que.getText()+"' , '"+mark.getSelectedItem()+"')";
       stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Question added in "+subi+" paper");
       que.setText(null);
       mark.setSelectedItem("1");
        }
          if(subi.equals("CS2")){
        String Query="INSERT INTO CS1(QUESTIONS,MARK)VALUES('"+que.getText()+"' , '"+mark.getSelectedItem()+"')";
       stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Question added in "+subi+" paper");
       que.setText(null);
       mark.setSelectedItem("1");
        }
       if(subi.equals("OOP2")){
        String Query="INSERT INTO OOP1(QUESTIONS,MARK)VALUES('"+que.getText()+"' , '"+mark.getSelectedItem()+"')";
       stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Question added in "+subi+" paper");
       que.setText(null);
       mark.setSelectedItem("1");
        }
       if(subi.equals("DS2")){
        String Query="INSERT INTO DS1(QUESTIONS,MARK)VALUES('"+que.getText()+"' , '"+mark.getSelectedItem()+"')";
       stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Question added in "+subi+" paper");
       que.setText(null);
       mark.setSelectedItem("1");
        }
       if(subi.equals("CS3")){
        String Query="INSERT INTO CS2(QUESTIONS,MARK)VALUES('"+que.getText()+"' , '"+mark.getSelectedItem()+"')";
       stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Question added in "+subi+" paper");
       que.setText(null);
       mark.setSelectedItem("1");
        }
       if(subi.equals("OOP3")){
        String Query="INSERT INTO OOP2(QUESTIONS,MARK)VALUES('"+que.getText()+"' , '"+mark.getSelectedItem()+"')";
       stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Question added in "+subi+" paper");
       que.setText(null);
       mark.setSelectedItem("1");
        }
       if(subi.equals("DS3")){
        String Query="INSERT INTO DS2(QUESTIONS,MARK)VALUES('"+que.getText()+"' , '"+mark.getSelectedItem()+"')";
       stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Question added in "+subi+" paper");
       que.setText(null);
       mark.setSelectedItem("1");
        }
       }
       catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(null,ex.toString());
       }
        
    }//GEN-LAST:event_addActionPerformed

    private void ownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownActionPerformed
Owner frame2=new Owner();
   addque.this.setVisible(false);
   frame2.setVisible(true);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ownActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Option frame234=new Option();
   addque.this.setVisible(false);
   frame234.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox mark;
    private javax.swing.JButton own;
    private javax.swing.JTextField que;
    private javax.swing.JComboBox subject;
    // End of variables declaration//GEN-END:variables
}
